import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const repoRoot = path.dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === 'production';

// The repository root doubles as a test vault, so builds are deployed straight into
// its plugin folder. Obsidian picks the new build up on plugin reload.
const vaultPluginDir = path.join(repoRoot, '.obsidian', 'plugins', 'better-paste');
const deployedFiles = ['main.js', 'manifest.json', 'styles.css'];

async function deployToVault() {
    await mkdir(vaultPluginDir, { recursive: true });
    await Promise.all(deployedFiles.map(file => copyFile(path.join(repoRoot, file), path.join(vaultPluginDir, file))));
}

// esbuild plugin that mirrors each successful build into the local test vault
const deployPlugin = {
    name: 'deploy-to-vault',
    setup(build) {
        build.onEnd(async result => {
            if (result.errors.length > 0) return;
            await deployToVault();
            console.log(`[deploy] ${vaultPluginDir}`);
        });
    }
};

// Node built-ins are marked external so esbuild never tries to bundle them into the plugin
const nodeBuiltins = builtinModules.flatMap(moduleName =>
    moduleName.startsWith('node:') ? [moduleName] : [moduleName, `node:${moduleName}`]
);

const context = await esbuild.context({
    banner: {
        js: banner
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    define: {
        'process.env.NODE_ENV': prod ? '"production"' : '"development"'
    },
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...nodeBuiltins
    ],
    format: 'cjs',
    target: 'es2022',
    charset: 'utf8',
    loader: {
        '.jpg': 'dataurl'
    },
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
    plugins: [deployPlugin]
});

if (prod) {
    await context.rebuild();
    await context.dispose();
    process.exit(0);
} else {
    await context.watch();
}
